CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL,
  Email NVARCHAR(255) NULL UNIQUE,
  Phone NVARCHAR(30) NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  StripeCustomerId NVARCHAR(120) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE AdminUsers (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Categories (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL,
  Slug NVARCHAR(140) NOT NULL UNIQUE,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Equipment (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  CategoryId INT NULL FOREIGN KEY REFERENCES Categories(Id),
  Name NVARCHAR(160) NOT NULL,
  Slug NVARCHAR(180) NOT NULL UNIQUE,
  Description NVARCHAR(MAX) NULL,
  PricePerRental DECIMAL(10,2) NOT NULL,
  TotalQuantity INT NOT NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  IsFeatured BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE EquipmentImages (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  EquipmentId INT NOT NULL FOREIGN KEY REFERENCES Equipment(Id) ON DELETE CASCADE,
  ImageUrl NVARCHAR(500) NOT NULL,
  SortOrder INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Orders (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NULL FOREIGN KEY REFERENCES Users(Id),
  OrderNumber NVARCHAR(40) NOT NULL UNIQUE,
  RentalDate DATE NOT NULL,
  StartTime TIME NOT NULL,
  EndTime TIME NOT NULL,
  ContactName NVARCHAR(120) NOT NULL,
  ContactEmail NVARCHAR(255) NULL,
  ContactPhone NVARCHAR(30) NULL,
  DeliveryMethod NVARCHAR(20) NOT NULL,
  DeliveryAddress NVARCHAR(400) NULL,
  DeliveryDistanceMiles DECIMAL(10,2) NOT NULL DEFAULT 0,
  DeliveryFee DECIMAL(10,2) NOT NULL DEFAULT 0,
  Subtotal DECIMAL(10,2) NOT NULL,
  Tax DECIMAL(10,2) NOT NULL,
  Discount DECIMAL(10,2) NOT NULL DEFAULT 0,
  Total DECIMAL(10,2) NOT NULL,
  PaymentStatus NVARCHAR(20) NOT NULL DEFAULT 'Pending',
  OrderStatus NVARCHAR(30) NOT NULL DEFAULT 'Pending',
  PayLater BIT NOT NULL DEFAULT 0,
  StripeCheckoutSessionId NVARCHAR(120) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE OrderItems (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(Id) ON DELETE CASCADE,
  EquipmentId INT NOT NULL FOREIGN KEY REFERENCES Equipment(Id),
  ItemName NVARCHAR(160) NOT NULL,
  Quantity INT NOT NULL,
  UnitPrice DECIMAL(10,2) NOT NULL,
  TotalPrice DECIMAL(10,2) NOT NULL
);

CREATE TABLE Payments (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(Id),
  Provider NVARCHAR(40) NOT NULL,
  ProviderPaymentId NVARCHAR(160) NULL,
  Amount DECIMAL(10,2) NOT NULL,
  Currency NVARCHAR(10) NOT NULL,
  Status NVARCHAR(20) NOT NULL,
  RawResponse NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Invoices (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(Id),
  InvoiceNumber NVARCHAR(40) NOT NULL UNIQUE,
  InvoiceDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  PdfUrl NVARCHAR(500) NULL,
  SentAt DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Settings (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  DeliveryPricePerMile DECIMAL(10,2) NOT NULL DEFAULT 0.75,
  MaxDeliveryDistanceMiles DECIMAL(10,2) NOT NULL DEFAULT 30,
  BusinessAddress NVARCHAR(400) NOT NULL,
  TaxRate DECIMAL(5,4) NOT NULL DEFAULT 0.0662,
  CompanyName NVARCHAR(200) NOT NULL DEFAULT 'Kids Party Rentals',
  SupportEmail NVARCHAR(255) NULL,
  SupportPhone NVARCHAR(30) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE CustomerAddresses (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
  Label NVARCHAR(60) NULL,
  AddressLine NVARCHAR(400) NOT NULL,
  IsDefault BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE CustomerPaymentMethods (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
  StripeCustomerId NVARCHAR(120) NOT NULL,
  StripePaymentMethodId NVARCHAR(120) NOT NULL,
  CardBrand NVARCHAR(40) NULL,
  Last4 NVARCHAR(4) NULL,
  ExpMonth INT NULL,
  ExpYear INT NULL,
  IsDefault BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE CustomerActivityLog (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
  OrderId INT NULL FOREIGN KEY REFERENCES Orders(Id),
  ActionType NVARCHAR(80) NOT NULL,
  Details NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE AdminNotes (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
  AdminUserId INT NOT NULL FOREIGN KEY REFERENCES AdminUsers(Id),
  Note NVARCHAR(MAX) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE OrderStatusHistory (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(Id) ON DELETE CASCADE,
  PreviousStatus NVARCHAR(30) NULL,
  NewStatus NVARCHAR(30) NOT NULL,
  ChangedByType NVARCHAR(20) NOT NULL,
  ChangedById INT NULL,
  Notes NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

INSERT INTO Settings (BusinessAddress) VALUES ('25 Monroe Ave, Toms River, NJ 08755');
